# See https://docs.ansible.com/ansible/latest/dev_guide/collections_galaxy_meta.html

namespace: community
name: hrobot
version: 1.2.3
readme: README.md
authors:
  - Felix Fontein (github.com/felixfontein)
description: Modules for controlling Hetzner's Robot
license_file: COPYING
tags:
  - hetzner
  - robot
  - failover
  - failoverip
  - firewall
repository: https://github.com/ansible-collections/community.hrobot
documentation: https://docs.ansible.com/ansible/devel/collections/community/hrobot/
homepage: https://github.com/ansible-collections/community.hrobot
issues: https://github.com/ansible-collections/community.hrobot/issues
build_ignore:
  - .gitignore
  - changelogs/.plugin-cache.yaml
